# Generated by Django 5.1.4 on 2025-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
